### ISSUE TITLE
Code Demo: Strong demo blogpost requested for PyTorch DP (differential privacy) library!

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/writing#101]
## Description
If you decide to pick this up, please DM @trask for all the details.

But the TLDR for this is that we would like to create a demo blogpost for (https://github.com/facebookresearch/pytorch-dp) within the next 3 weeks. The demo would be to take one of the existing tutorials in the codebase and pair it down to something extremely simple. Then walk through the demo step by step and teach it along with the corresponding DP concepts it references.

It's a *really* exciting project but I can't say why here! DM me on slack if you decide to pick it up.

**Comment by shaistha24** [comment]
@iamtrask I am interested in working on this.

**Comment by Metrix1010** [comment]
I'm interested in this as well.

**Comment by em-blue** [comment]
@iamtrask can you give @Kritikalcoder and @shaistha24 what they need? 
@Metrix1010 you're welcome to take just an editorial role or help in the code demo as well

**Comment by Kritikalcoder** [comment]
Taking this up actively starting today :)

**Comment by Kritikalcoder** [comment]
Published: https://blog.openmined.org/differentially-private-deep-learning-using-opacus-in-20-lines-of-code/
