### ISSUE TITLE
Blog: Key Challenges in Federated Learning

### ISSUE THREAD

**Issue by pengyuan-zhou** [OpenMined/writing#102]
To summarize the key challenges in the development of FL, and potential challenges may come in the near future, plus some arising solutions that seem promising to tackle the challenges.

**Comment by wenhuizhang** [comment]
@pengyuan-zhou hi, are you still working on this issue please?

**Comment by Metrix1010** [comment]
Hi @pengyuan-zhou can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
