### ISSUE TITLE
Announcement: OpenMined is officially listed as a Digital Public Good!!! https://digitalpublicgoods.net/explore/#OpenMined

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#104]
Announce that OpenMined is listed as a Digital Public Good!

What is a Digital Public Good: "The UN Secretary-General’s High-level Panel on Digital Cooperation, in its report published on June 10th 2019, recommends “that a broad, multi-stakeholder alliance, involving the UN, create a platform for sharing digital public goods, engaging talent and pooling data sets, in a manner that respects privacy, in areas related to attaining the SDGs”.
We define Digital Public Goods as open source software, open data, open AI models, open standards and open content that adhere to privacy and other applicable best practices, do no harm and are of high relevance for attainment of the UN’s 2030 Sustainable Development Goals (SDGs)."

**Comment by dA505819** [comment]
@em-blue Shared the link on Slack. :)

**Comment by dA505819** [comment]
Here it is:
https://blog.openmined.org/openmined-is-officially-listed-as-a-digital-public-good/
