### ISSUE TITLE
Blog: Follow up on Privacy Preserving Federated Learning against GAN attacks.

### ISSUE THREAD

**Issue by PnkUncrn** [OpenMined/writing#107]
Follow up on the post: https://blog.openmined.org/how-gans-can-cause-a-privacy-breach-in-federated-deep-learning/

**Comment by balapriyac** [comment]
Hi @PnkUncrn could you pls share updates on this?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
