### ISSUE TITLE
How to contribute to open source at OpenMined for beginners

### ISSUE THREAD

**Issue by Kritikalcoder** [OpenMined/writing#109]
## Where?
Beginner's blog for contributing to OpenMined's projects

## Who?
Beginners joining the community

## What?
Help complete beginners make their first successful pull request merged.

## Additional Context
Could be in context specific to PySyft. Open to discussing this.

**Comment by dwvicy** [comment]
@Kritikalcoder how different should this blog be from the welcome package? Is it like specific to contributing to one repository (like PySyft)

**Comment by Metrix1010** [comment]
Hi @dwvicy can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
