### ISSUE TITLE
Privacy Teaching Series: Privacy by Shuffling

### ISSUE THREAD

**Issue by NateSolon** [OpenMined/writing#11]
Introduction to privacy by shuffling
https://docs.google.com/document/d/1Z-NPKFF8CbQ1GGtsDfou6HaP36xzVZ2nuvk7VFiitas/edit

**Comment by em-blue** [comment]
@NateSolon How are things? Good to launch? :-)

**Comment by em-blue** [comment]
https://blog.openmined.org/differential-privacy-by-shuffling/
