### ISSUE TITLE
Code Demo: Laplacian Mechanism

### ISSUE THREAD

**Issue by NateSolon** [OpenMined/writing#110]
Jupyter Notebook exploring the Laplacian Mechanism: what it is and why it's used for DP.

**Comment by NateSolon** [comment]
Link to draft: https://colab.research.google.com/drive/1CyQetMUbdszLLIB78M-iR74eIRwJR0rU?usp=sharing

**Comment by chinmayshah99** [comment]
hi @NateSolon 
This looks great. Couple of suggestions: 
1. Maybe link to a detail explanation of what laplacian distribution is. Probably a wiki article or some khanacademy tutorial?
2. When epsilon is introduced, it becomes a bit difficult to make context. Like where did epsilon come from? What is it's significance? What does it mean?
3. There is the last statement `**According** to ε differential privacy, these should not differ by a factor of more than e<sup>ε</sup>.` We can expand a bit in this? Why should it not differ?

**Comment by NateSolon** [comment]
@chinmayshah99 Thanks for the feedback! I made some revisions based on your comments.

Let me know if it makes more sense now. To be honest the parts you called out are the most confusing for me as well, but I tried to add some more explanation.

**Comment by chinmayshah99** [comment]
Is it the same link?
I can't see changes for the (3).

**Comment by NateSolon** [comment]
Yep, same link. I added a lot earlier in that section to try to make it clearer. Added some more to the end just now as well.

**Comment by chinmayshah99** [comment]
LGTM! A good idea would be to run it by someone who hasn't seen this notebook.

**Comment by NateSolon** [comment]
Hi @chinmayshah99 would you like to include this notebook in the examples for PyDP? I think I will put a link to the colab on the OpenMined blog, but we could also include it in the examples directory if you think that makes sense.

**Comment by chinmayshah99** [comment]
Sure, why don't you send a PR!

**Comment by Metrix1010** [comment]
@AbinavRavi what is the status of this issue?

**Comment by AbinavRavi** [comment]
I dont know the status
