### ISSUE TITLE
Conference Talk Summary: Helen Nissenbaum - Privacy, Contextual Integrity, and Obfuscation

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#113]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by Metrix1010** [comment]
[https://docs.google.com/document/d/1lclgC2wZE-H17CkVz17WKHmNIkCmPjLHkXW6wGRCV6c/edit](url)

**Comment by em-blue** [comment]
@claudiaghezzou you'd be a well suited editor for this one

**Comment by Metrix1010** [comment]
A more up to date version is a DRAFT on Ghost. Please see that version.

**Comment by claudiaghezzou** [comment]
Amazing, thanks Emma!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
