### ISSUE TITLE
Conference talk summary: Ronnie Falcon - Governance roadmap

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#115]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by Metrix1010** [comment]
https://docs.google.com/document/d/1nGcsVXCxHmEHRrsHMPX9KN_xUlD0rIbxK9-I35i0Qhs/edit
Notes

**Comment by Metrix1010** [comment]
HI @em-blue can you provide a status update on this issue?

**Comment by BhaswatiRoy** [comment]
Hello
If this issue is open for work, I can work on the summarization

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
