### ISSUE TITLE
Conference talk summary: Bob Rogers - accelerating deployment of healthcare ai by 1000x

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#118]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by ZinaSar** [comment]
@bikramb98 , do you need help here? we could split the videos and finish the script earlier. what do you think?

**Comment by bikramb98** [comment]
Thanks Zina! Messaged you on Slack.

**Comment by balapriyac** [comment]
Hi @bikramb98 and @ZinaSar pls feel free to reach out to me if you need any help. :)

**Comment by aqua-one** [comment]
@bikramb98 @ZinaSar 
Hi there, 
We are wondering if either or both of you can work to complete this one? 
This topic is good for leading up to the release of Course 3 - which is right around the corner!

Please let us know if you need help or if you would like it re-assigned. :)

**Comment by Arya-Gupta** [comment]
Hello, I want to work on this issue. It would be great if it could be assigned to me.

**Comment by Metrix1010** [comment]
Hi @bikramb98 please provide a status update on this issue. Thanks :)

**Comment by Arya-Gupta** [comment]
https://blog.openmined.org/accelerating-deployment-of-healthcare-ai-by-1000x/
