### ISSUE TITLE
Conference talk summary - Georgios Kaissis - End-to-end privacy preserving deep learning on multi-institutional medical imaging data

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#119]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by AbinavRavi** [comment]
Hello Please find the draft of the blog https://docs.google.com/document/d/1tksTY7I_cbv_3xapgnBQsMQcVAlyKRGj_uTo8cUAOsY/edit?usp=sharing 
Please review and let me know if I can publish.

**Comment by AbinavRavi** [comment]
Final published version can be found at  https://blog.openmined.org/conference-summary-end-to-end-privacy-preserving-deep-learning-on-multi-institutional-medical-imaging-data/
