### ISSUE TITLE
Privacy Teaching Series: What is Homomorphic Encryption?

### ISSUE THREAD

**Issue by AntonioLopardo** [OpenMined/writing#12]
[Link to Ghost draft](https://blog.openmined.org/ghost/#/editor/post/5e4d062322887907e088ec68)

**Comment by em-blue** [comment]
Hey @Metrix1010 would you like to try this for your first editing project? The content itself has been approved, just want to edit for language, flow etc.

**Comment by Metrix1010** [comment]
Yes of course! I'll have a look. Thanks :)

**Comment by Metrix1010** [comment]
Went through the entire post and tweaked it slightly.

Under "Use Cases" there is a missing link. "Click here for a more in-depth look at these applications." 
Please link it up Antonio or adjust as you intended. If you want me to delete it I can do that as well. Just let me know.

After the above is resolved, it is ready to "Publish".

Great post and lots of links to resources 👍 
Laura
