### ISSUE TITLE
Conference talk summary: Maddie shang - AI Powered UX with OpenMined

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#125]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by jaintj95** [comment]
@dwvicy Are you still working on this or is it fine by you if I pick it up? :)

**Comment by dwvicy** [comment]
> @dwvicy Are you still working on this or is it fine by you if I pick it up? :)

Yeah working on this, just had exams and stuff in between so had to hit pause! I hope you find another issue :)

**Comment by jaintj95** [comment]
> > @dwvicy Are you still working on this or is it fine by you if I pick it up? :)
> 
> Yeah working on this, just had exams and stuff in between so had to hit pause! I hope you find another issue :)

Awesome. Good luck! :)

**Comment by balapriyac** [comment]
Hi @dwvicy,
Hope the draft is coming along. Pls reach out if you need help.

**Comment by balapriyac** [comment]
@dwvicy , If you'd like to collaborate with @jaintj95 that'd be great too!

**Comment by balapriyac** [comment]
@dwvicy I can see that you've assigned yourself another issue as well.
It has been really long since you've assigned the issue to yourself. 
Kindly update on the progress of your drafts. I had also reached out to you before a few weeks.
Else, we may have to remove assignment so that other members of the team can work on this.

**Comment by dwvicy** [comment]
Working on this, I'll send in the draft by Tuesday!

**Comment by dwvicy** [comment]
Sorry for the delay! :(
