### ISSUE TITLE
Conference Talk Summary: Sasi Kurakonda - ML Privacy Meter: Aiding Regulatory Compliance by quantifying the privacy risks of machine learning

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#128]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by chandni1003** [comment]
@balapriyac Please assign me to this.

**Comment by balapriyac** [comment]
Done @chandni1003 :)

**Comment by Arya-Gupta** [comment]
@Metrix1010 I am interested in working on this issue. Please assign it to me.

**Comment by Arya-Gupta** [comment]
https://blog.openmined.org/ml-privacy-meter-aiding-regulatory-compliance-by-quantifying-the-privacy-risks-of-machine-learning/

**Comment by Metrix1010** [comment]
Thanks @Arya-Gupta!
