### ISSUE TITLE
Conference talk summary: Kenneth Cukier (senior editor at the Economist) - Closing Session Keynote

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#129]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by callezenwaka** [comment]
Hi @em-blue,

I would like to take up this issue.

Regards

**Comment by Metrix1010** [comment]
@callezenwaka were you able to get your piece reviewed by an editor?

**Comment by callezenwaka** [comment]
Hi Laura,
This was reviewed by Sukanya and published here [link](https://blog.openmined.org/the-impact-of-privacy-regulation-on-effective-deployment-of-technology-during-the-covid-19-pandemic/)
