### ISSUE TITLE
Conference talk summary: Amber Trask - Where do you fit within our community?

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#130]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by prantik-pdeb** [comment]
@em-blue I want to give a try.

**Comment by divyadixit** [comment]
Hello, @em-blue, I've recently joined the team. Is it still open to be worked on (I saw it on the long form and announcements to-do board)? Can I give it a try?

**Comment by prantik-pdeb** [comment]
Hi @divyadixit I am working on this, waiting for the presentation day slides to add more information. Otherwise I am ready to publish it.

**Comment by divyadixit** [comment]
Thanks for the reply @prantik-pdeb.

**Comment by balapriyac** [comment]
@prantik-pdeb could you pls share updates on this post?
