### ISSUE TITLE
Conference Demo summary: Alan Aboudib - SyferText 0.1.0 Privacy-preserving NLP Over PyGrid

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#132]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by IrinaMBejan** [comment]
I started working on it, but it seems most content overlaps with https://blog.openmined.org/securing-nlp-syfertext-demo-alan/
and
https://blog.openmined.org/encrypted-training-medical-text-syfertext/

I decided with @balapriyac to mark it done and avoid duplicating the content on the blog. If there are other views, feel free to reopen the issue and I would be happy to finish and publish the initial article.
