### ISSUE TITLE
Conference Demo summary: Privacy Preserving Vertically Distributed Machine Learning

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#135]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by IrinaMBejan** [comment]
The content of the presentation overlaps with  https://blog.openmined.org/what-is-pyvertical/ and agreed with @balapriyac to mark it as done to not have duplicated content on the blog.
