### ISSUE TITLE
Conference demo summary: Introduction to TFHE and some applications

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#136]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by wenhuizhang** [comment]
@AbinavRavi  Hi, Abninav , could I grab this issue please?

**Comment by AbinavRavi** [comment]
Sure

**Comment by wenhuizhang** [comment]
Working on this video summary now https://www.youtube.com/watch?v=nn2fFpO4p9Q&list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6&index=6

**Comment by emharsha1812** [comment]
Is this issue still open? If yes, Can you please assign this to me?

**Comment by Metrix1010** [comment]
@wenhuizhang, @emharsha1812 would like to write this piece. Can you provide an update on the status of it? Thanks :)

**Comment by wenhuizhang** [comment]
> @wenhuizhang, @emharsha1812 would like to write this piece. Can you provide an update on the status of it? Thanks :)

Sure :) I'd like to

**Comment by Metrix1010** [comment]
Go ahead with this one @emharsha1812

**Comment by emharsha1812** [comment]
Okay cool! Working on it

**Comment by emharsha1812** [comment]
This blog is published! |
https://blog.openmined.org/introduction-to-thfe-and-its-applications/
