### ISSUE TITLE
Conference demo summary: Privacy-preserving medical imaging analysis with OpenMined and PriMIA. A sneak peak at features and concepts

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#138]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by balapriyac** [comment]
After going over the content of the talk, the repo of PriMIA already has a comprehensive video walkthrough and a blog post would end up replicating a substantial portion of [How-To guides](https://g-k.ai/PriMIA/HowTo)/, [Library Documentation](https://g-k.ai/PriMIA/CLI_Docs/).
