### ISSUE TITLE
Conference demo summary: differentially private model training with Opacus

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#139]
We want to summarise/transcribe people’s talks from the conference to help increase the reach of their talk and make it easier for people to browse the key takeaways from the conference. 

Find the schedule of the talk here: https://pricon.openmined.org/agenda
And the recording of the talk here: https://www.youtube.com/playlist?list=PLUNOsx6Az_ZGKQd_p4StdZRFQkCBwnaY6

If the speaker is an OpenMined member, feel free to ask them for a copy of their slides - otherwise, you can screenshot key parts from their slides.

**Comment by divyadixit** [comment]
@em-blue I'd like to give this a try but can't seem to find the recording of this talk in this the playlist.

**Comment by cescapa** [comment]
@divyadixit you are right! the video can be found here: https://www.youtube.com/watch?v=MWPwofiQMdE&feature=emb_logo 
if you want to lead, I'd be happy to collaborate with editing

**Comment by balapriyac** [comment]
That'd be great! As ghost platform allows authors collaborating on an
article to joint publish, it'd be great if both of you could collaborate on
this demo summary :)

**Comment by divyadixit** [comment]
> @divyadixit you are right! the video can be found here: https://www.youtube.com/watch?v=MWPwofiQMdE&feature=emb_logo
> if you want to lead, I'd be happy to collaborate with editing

Thanks a bunch @cescapa! I'll be happy to collaborate with you on editing 💯

**Comment by divyadixit** [comment]
Assigning the issue to myself based on the conversation with @balapriyac :)

**Comment by balapriyac** [comment]
As discussed with @divyadixit we found content with considerable overlap on Differentially Private Model Training with Opacus on the OM blog. Hence, marking is done.
https://blog.openmined.org/pysyft-opacus-federated-learning-with-differential-privacy/
https://blog.openmined.org/differentially-private-deep-learning-using-opacus-in-20-lines-of-code/
