### ISSUE TITLE
Beginner-friendly OM terminology

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#155]
- PyVertical to PyDentity

**Comment by lzeladam** [comment]
@balapriyac I can research this topic and add content to the document =)

**Comment by balapriyac** [comment]
Great, thank you Alexander Zelada :)

**Comment by cescapa** [comment]
> @balapriyac I can research this topic and add content to the document =)

@lzeladam please let me know if you would like some help. If you come up with the list of terms that we should provide definitions for, I can definitely help with the wording and making it readable by general audiences.

**Comment by lzeladam** [comment]
> > @balapriyac I can research this topic and add content to the document =)
> 
> @lzeladam please let me know if you would like some help. If you come up with the list of terms that we should provide definitions for, I can definitely help with the wording and making it readable by general audiences. 

Hi @cescapa I was reading more about this concepts because these are new to me, but if you can help me I would really appreciate it.

**Comment by cescapa** [comment]
> > > @balapriyac I can research this topic and add content to the document =)
> > 
> > 
> > @lzeladam please let me know if you would like some help. If you come up with the list of terms that we should provide definitions for, I can definitely help with the wording and making it readable by general audiences.
> 
> Hi @cescapa I was reading more about this concepts because these are new to me, but if you can help me I would really appreciate it.

Sure please go ahead and create the Gdoc and start to enter terms that we should define. I will start to research and enter definitions, or make suggestions.

**Comment by gonzalo-munillag** [comment]
Hi guys,
If you want to define terminology, I invite you to have a look at the Terminology section of this publication ["Revealing the landscape of privacy-enhancing technologies in the context of data markets for the IoT: a systematic literature review"](https://arxiv.org/abs/2107.11905). 
If you want clarifications, feel free to contact me gonzalo.munilla-garrido@tum.de

**Comment by gonzalo-munillag** [comment]
Additionally, it does not only provide a list of terms in that section, ["Revealing the landscape of privacy-enhancing technologies in the context of data markets for the IoT: a systematic literature review"](https://arxiv.org/abs/2107.11905) also describes every PET in a few paragraphs. You could also use that to compile a set of definitions for each PET.

**Comment by Metrix1010** [comment]
Hi @lzeladam can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Hi @lzeladam I'll be closing this issue for now. Let me know if you'd like it reopened.
