### ISSUE TITLE
Encrypted Deep Learning article in the privacy teaching series

### ISSUE THREAD

**Issue by AntonioLopardo** [OpenMined/writing#16]
[Link to Ghost draft](https://blog.openmined.org/ghost/#/editor/post/5e5e513022887907e088f654)

**Comment by Metrix1010** [comment]
Hi @AntonioLopardo can you provide a status update on this issue?

**Comment by AntonioLopardo** [comment]
Sorry @Metrix1010, I've not made any progress on this and won’t have the time to work on it, apologies for the lack of updates

**Comment by Metrix1010** [comment]
No worries. Thanks for the update!

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
