### ISSUE TITLE
Conference Talk Summary: Superfast Differential Privacy

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#162]
Talk by Pranav Subramani at PriCon 2020 

Key Idea: Use JAX for rapid prototyping!

Video Link: https://www.youtube.com/watch?v=k7ew0Rz8pTg

**Comment by jabertuhin** [comment]
unasssigning myself from this task for now, as I will be busy in the upcoming days. Sorry for the inconvenience.

**Comment by bushra2001** [comment]
@balapriyac Kindly, assign me this task.

**Comment by BhaswatiRoy** [comment]
Hello
I would like to work on summarizing the talk in the conference
It would be great if this issue could be assigned to me

**Comment by Metrix1010** [comment]
https://blog.openmined.org/superfast-differential-privacy/
