### ISSUE TITLE
Blog: Why should you take course 1 of the Private AI Series?

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#165]
Another interesting post :)
Here's what the post can possibly talk about:
How has `Our Privacy Opportunity` changed your perspective and  understanding of privacy? 
How do you like the community and mentorship support at OpenMined?
Which parts of the course did you enjoy the most?
How excited are you  for the rest of the Private AI series?

**Comment by balapriyac** [comment]
@cescapa would be great if you could consider writing this up for us :)

**Comment by cescapa** [comment]
Yes, happy to take this one. 
Please advise what is meant by priority 2? How many days to draft and to publishing?

**Comment by balapriyac** [comment]
Hi Carlos,
There are no hard or soft deadlines, but I've prioritized it 'high' as it
would benefit the community if it's posted soon enough. You may take your
time with the draft. :)

**Comment by NemaVatsala** [comment]
Hey, Could I contribute to this as well? Since I am currently taking this course, I might be able to add a few points for the new version, which also ensures accountability for completion :P.

**Comment by balapriyac** [comment]
Sure Vatsala. Your views are always welcome. :)

**Comment by dhreb** [comment]
Has this already been written? Found it in the TO-DO section of the project board. Just wondering because I would be willing to take it if it hasn't been taken on already!

**Comment by balapriyac** [comment]
@bottomparm I'm sorry - this idea would be archived as we have another upcoming blog series on students' experience in the Private AI Series
