### ISSUE TITLE
Conference Talk Summary: Driving Enterprise Adoption of Federated Learning and Differential Privacy

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#166]
Link to the recording: https://www.youtube.com/watch?v=J1AaRN72l0k

**Comment by seethumia** [comment]
@balapriyac

**Comment by balapriyac** [comment]
Hi Seethu. I've assigned you the issue :)

**Comment by seethumia** [comment]
Thanks Bala.

**Comment by Metrix1010** [comment]
Hi @seethumia can you provide a status update on this issue?

**Comment by seethumia** [comment]
https://docs.google.com/document/d/1AkJnE2NiAMj8lOJZwZMz8U5UuSbIDEWz4qqdkxhh6MM/edit

The doc is ready for review.

**Comment by Metrix1010** [comment]
Delayed in reviewing this @seethumia my apologies. Did you get this published yet?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
