### ISSUE TITLE
Conference Talk Summary: Pragmatic Security for Collaborative Learning

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#167]

**Comment by eswarijayakumar** [comment]
@balapriyac Hi, I like to work on this talk summary. Can you please assign this issue to me

Youtube link - https://www.youtube.com/watch?v=oQ5qmE00FNk

**Comment by balapriyac** [comment]
Hi Eswari, we've received your application to join the writing team. Pls
reach out to @Bala on Slack for the next steps.

**Comment by eswarijayakumar** [comment]
That's great @balapriyac . DM-ed you in slack.

**Comment by balapriyac** [comment]
Hi @eswarijayakumar, did you get a chance to listen to the video and see if it interests you. If yes, I'll go ahead and assign it to you if you'd like to try.

**Comment by eswarijayakumar** [comment]
Hi @balapriyac Yes, I'll work on this blog post this weekend. Please assign it to me.

Also In the same Video, there is another talk on "Falcon: Honest-Majority Maliciously Secure Framework for Private Deep Learning" by Sameer Wagh. If a blog on that particular talk summary is a good idea to be added in OpenMined, I'll add it as a new issue. Kindly confirm on that.

**Comment by balapriyac** [comment]
The Falcon talk did not have audio if I remember correctly, hence it's not
included.

**Comment by eswarijayakumar** [comment]
Thanks for the reply !! The [Falcon talk](https://youtu.be/oQ5qmE00FNk?t=605) has audio but I am not sure whether the talk is completely available in the video. It seemed to be stopped abruptly.

**Comment by balapriyac** [comment]
Hi @eswarijayakumar I have assigned the issue to you. You may start working on the draft :)

**Comment by Metrix1010** [comment]
Hi @eswarijayakumar how is this post coming along? Anything I can help with? If you are working on a different post just let me know. Thanks :)

**Comment by eswarijayakumar** [comment]
Hi @Metrix1010 , I am planning to submit the draft of this blog post for review by this weekend.

**Comment by plau51ble** [comment]
Closing this issue as it was published under the blog:
https://blog.openmined.org/pragmatic-security-for-collaborative-learning/
