### ISSUE TITLE
Blog: Federated Learning of Cohorts (FLoC) - An overview

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#168]
Why FLoC isn't a great idea!

**Comment by jabertuhin** [comment]
I will work on this, and share the document with you.

**Comment by jabertuhin** [comment]
I won't be able to continue working on this blog post. Sharing the resources I went through before starting writing and found helpful -

- [What is Federated Learning of Cohorts (FLoC)?](https://web.dev/floc/)
- [Building a privacy-first future for web advertising](https://blog.google/products/ads-commerce/2021-01-privacy-sandbox/)
- [POV: Google’s Federated Learning of Cohorts (FLoC)](https://www.mindshareworld.com/news/pov-googles-federated-learning-of-cohorts-floc)
- [PRIVACY AND ADS IN CHROME ARE ABOUT TO BECOME FLOCING COMPLICATED](https://www.theverge.com/2021/3/30/22358287/privacy-ads-google-chrome-floc-cookies-cookiepocalypse-finger-printing)
- [FLoC Origin Trial & Clustering](http://dev.chromium.org/Home/chromium-privacy/privacy-sandbox/floc)
- [What is Federated Learning of Cohorts (FLoCs)?](https://streetfightmag.com/2021/02/01/what-is-federated-learning-of-cohorts-flocs/#.YJrkHKIzaV4)
- [FLoC to It – How the Federated Learning of Cohorts Affects Privacy](https://infotrust.com/articles/floc-to-it-how-the-federated-learning-of-cohorts-affects-privacy/)
- [Privacy analysis of FLoC](https://blog.mozilla.org/en/mozilla/privacy-analysis-of-floc/)
- [FLOC-Whitepaper-Google.pdf](https://github.com/google/ads-privacy/blob/master/proposals/FLoC/FLOC-Whitepaper-Google.pdf)

**Comment by balapriyac** [comment]
No problem Jaber.
There's already a lot written.
Let's drop this blogpost idea :)
Pls remove assignment and close the issue. And move it to the Done column
