### ISSUE TITLE
Privacy Teaching Series: HE Video

### ISSUE THREAD

**Issue by AntonioLopardo** [OpenMined/writing#17]
Outline:
Video based on the HE article in the series with an emphasis on visual explanations.

**Comment by Metrix1010** [comment]
I watched the video Antonio and it was really great! Awesome work.

I caught a few spelling mistakes at these locations:

1:24 Disadvantages
1:28 kinds  +  concerns
3:08 significant
9:27 corrupting
10:42 technique

That's all 👍 
Laura

**Comment by AntonioLopardo** [comment]
Hi Laura! I'm glad you liked it and thank you for taking the time to watch it☺️
I'll fix these typos and upload a correct version asap, https://youtu.be/E29ivefMfDQ, this is the most up-to-date version as of right now.

**Comment by Metrix1010** [comment]
Please ping me when the video is updated and I'll mark it done :)

**Comment by AntonioLopardo** [comment]
Here it is https://youtu.be/EUqgQjMZy_Y, with subtitles now👍
