### ISSUE TITLE
A survey of Homomorphic Encryption frameworks

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#175]
A survey analyzing the different frameworks for HE.
TenSEAL, MS SEAL etc.

**Comment by AbinavRavi** [comment]
@balapriyac  is this open, Can I take it up?

**Comment by balapriyac** [comment]
Hi Abinav, Absolutely.
Pls proceed with this. :)

**Comment by wenhuizhang** [comment]
Thanks @AbinavRavi , I will grab this one ;)
