### ISSUE TITLE
A survey of Differential Privacy frameworks

### ISSUE THREAD

**Issue by balapriyac** [OpenMined/writing#178]

**Comment by balapriyac** [comment]
@znreza would you like to collaborate on this?
The objective is to give a comprehensive list of frameworks for 

- Federated Learning
- Homomorphic Encryption 
- Differential Privacy

These would ideally be three posts going to the OM blog at equally spaced intervals.
We should try and get the first one (on FL) by July end.

**Comment by znreza** [comment]
@balapriyac Sure I will be happy to collaborate!

**Comment by emharsha1812** [comment]
Please assign this to me

**Comment by znreza** [comment]
Done!

**Comment by Metrix1010** [comment]
https://blog.openmined.org/a-survey-of-differential-privacy-frameworks/
is published! Thanks @emharsha1812
