### ISSUE TITLE
Holistic classification of PETs

### ISSUE THREAD

**Issue by gonzalo-munillag** [OpenMined/writing#182]
## What?
The publication ["Revealing the landscape of privacy-enhancing technologies in the context of data markets for the IoT: a systematic literature review"](https://arxiv.org/abs/2107.11905) classifies the different PETs and other technologies that sometimes are confused with PETs.

There has not been a classification with such breadth, and most importantly, systematization. 

Creating a blog post summarizing the classification using Table 2 and Fig. C11 will bring this research to a broader audience.

## How long?
As short as possible including Table 2 and Fig. C11.

## Is your research related to a problem?
There is a lot of fuzziness about which are the PETs and what are not and their specific use.

## Additional Context
Kindly contact me (gonzalo.mg.munilla-garrido@tum.de) for further questions.

### Resources

[Table 2](https://github.com/OpenMined/writing/files/6974925/Tech_Challenge_Master.pdf)

[Fig C.11 without challenges](https://github.com/OpenMined/writing/files/6974966/Detailed_Tree.pdf)

[Summary of Fig C.11](https://github.com/OpenMined/writing/files/6974918/PET.tree.ppt.pdf)

**Comment by plau51ble** [comment]
Hi @gonzalo-munillag If this issue is available then I would like to work on it.

**Comment by Metrix1010** [comment]
@gonzalo-munillag and @plau51ble is this issue being worked on? Please provide a status update. Thanks :)

**Comment by sfmajors373** [comment]
@gonzalo-munillag Hi, the ticket says to include table 2, but in the resources table 3 is linked.  Which do we actually want to include in the blog post?  Both/either seem very informative.

**Comment by sfmajors373** [comment]
Blog post published: https://blog.openmined.org/p/6059b917-6a88-4e38-a0a3-0e4bca1f021e/

**Comment by gonzalo-munillag** [comment]
Awesome!
