### ISSUE TITLE
Classification of challenges facing PETs

### ISSUE THREAD

**Issue by gonzalo-munillag** [OpenMined/writing#183]
## What?
The publication ["Revealing the landscape of privacy-enhancing technologies in the context of data markets for the IoT: a systematic literature review"](https://arxiv.org/abs/2107.11905) classifies the different PETs and other technologies that sometimes are confused with PETs. Furthermore, there is a complete section dedicated to classifying the problems that PETs face. They are summarized in Fig. 8. Additionally, it contains table 1 explaining the issues that the IoT will bring in the domain of privacy.

A blog post that summarized this challenges would bring a lot of clarity to a broader audience.

## How long?
As short as possible, as long as it summarizes succinctly the challenges with definitions and includes Fig. 8 and Table 1.

## Is your research related to a problem?
Literally the problems that PETs face.

## Additional Context
Kindly contact me (gonzalo.mg.munilla-garrido@tum.de) for further questions.

## Resources

[Overview of challenges for PETs in the IoT.pdf](https://github.com/OpenMined/writing/files/6975014/challenges_PETs_IoT.pdf)

Here is the table, Overview of challenges brought by the IoT paradigm into PETs:

| Challenge | Description | Impact of privacy | 
|:-------|:-----|:-----|
Heterogeneity and Interoperability |The IoT consists of billions of IoT devices from different manufacturers, running different software on different local networks and geographic regions, with different computation power and storage capacity. Furthermore, different com- munications standards, connectivity and availability aggravate the interplay of IoT devices. | An IoT data market should be agnostic to these differences and minimize any additional requirements; however, it is unclear how global data markets should harmonize data coming from different jurisdictions with different privacy regulations and how an IoT device can interact with another whose, e.g., verification schemata are inadequate from its perspective. In addition to these obstacles, a lack of interoperability may re- strain PETs that involve the communication between many devices, e.g., SMC. |
Computation power | Manufacturers produce many IoT devices designed to consume low energy and require minimal volume, limiting these IoT devices to the core functionalities of monitoring and communication  | Any additional computation requires a higher investment in resources and manufacturing, and running some PETs becomes infeasible without this extra investment. Consequently,  a set of PETs is excluded without more computation power, e.g., cryptography-based PETs such as HE, SMC, ZKP, some digital signatures, or consensus algorithms.This limitation, however, may only apply to contexts where it might not be possible to connect IoT devices acting as clients with proprietary or trusted third-party nodes where these PETs are executed. |
Storage capacity and real-time communication | Minimizing the physical volume of an IoT device reduces their price but limits their storage capacity, forcing IoT devices to transmit the data to a data warehouse or a data market as quickly as possible. This tendency intensifies in some IoT applications where the time delay tolerance is low to enhance the utility of real-time information | Processing time constrains the number of usable PETs, excluding those that require long execution times, such as fully homomorphic encryption or creating a zero-knowledge proof.|
Data quality | An unreliable IoT design may afflict thousands of IoT devices mass-produced by a manufacturer, which at deployment may lead to millions of unreliable data points. Furthermore, networks may also be unreliable, further worsening the quality.  | The impact may seem beneficial in terms of privacy; however, unreliable data leads to verification and secure computation schemata to fail and anonymization technologies to over-perturb the data as the underlying data is not entirely truthful.  |
Ambiguous data ownership | When purchasing a device or a cluster of IoT devices, e.g., a phone, consumers also expect to own the data they are generating. However, the phone manufacturer and service providers expect to receive parts of this data nowadays with meager consent. In addition to this clash of interests, there are scholars that ponder whether data belongs to anyone in the first place. | Having unclear data ownership leads to a misguided deployment of PETs, which may cause detrimental consequences if the privacy measures fall short. On the other hand, if the practitioner knows who has the right to the data and what the owner is reticent to share with a third party, then selected PETs and their privacy tuning can be optimized accordingly. |
Privacy disparity |  Depending on the IoT devices' deployment location, the degree of privacy measures should be higher or lower, e.g., sensors in vehicles, smart homes, phones, and wearables. Furthermore, IoT deployments should adapt the monitoring time to an adequate amount depending on the context.|  Some PETs, such as semantic and syntactic technologies, allow adjusting the degree of privacy; however, others are more rigid. Selecting and adapting a PET to the IoT devices' deployment context requires expertise.|
Pricing | There are multiple variables imposing the price of data aside from supply and demand: the truthfulness, the source, either purchasing the data or the access, and the privacy level. These factors add additional complexity to pricing, e.g., the sources have become disparate with the IoT, which drives pricing to a more granular task than before, when aggregated data could be sold as a unit. | Aside from payment enforcement mechanisms, pricing involves negotiations, which frequently must ensure privacy. This adds an extra layer of complexity to the deployment of PETs.Furthermore, as data markets trade with more granular data points, PETs that need aggregation might be excluded in some contexts, e.g., syntactic technologies such as k-anonymity. |

**Comment by callezenwaka** [comment]
Hi @AbinavRavi,
I would like to take up this piece. I will reach out to @gonzalo-munillag for more details.

**Comment by callezenwaka** [comment]
Hi,
I think it is about time we closed this issue.

Thanks

**Comment by AbinavRavi** [comment]
https://blog.openmined.org/classifying-the-challenges-of-privacy-enhancing-technologies-pets-in-iot-data-markets/
