### ISSUE TITLE
Future work and insights in the field of PETs and the IoT

### ISSUE THREAD

**Issue by gonzalo-munillag** [OpenMined/writing#184]
## What?
The publication ["Revealing the landscape of privacy-enhancing technologies in the context of data markets for the IoT: a systematic literature review"](https://arxiv.org/abs/2107.11905) classifies the different PETs and other technologies that sometimes are confused with PETs. 

Its Discussion and Conclusion sections contain a set of key findings and future work that, if parsed/summarized correctly, can bring motivation and a clear path to researchers.

## How long?
2-3 pages with font size 11.

## Is your research related to a problem?
Future research and warnings in the field of PETs.

Kindly contact me (gonzalo.mg.munilla-garrido@tum.de) for further questions.

**Comment by callezenwaka** [comment]
Hi @AbinavRavi,
I'd like to take this up. I'd be reaching out to @gonzalo-munillag for further clarities if any.

**Comment by gonzalo-munillag** [comment]
Feel free to reach out to me @callezenwaka :)

**Comment by callezenwaka** [comment]
I think we can close up this.

**Comment by Metrix1010** [comment]
Thanks Callis :)
