### ISSUE TITLE
Update to Duet blog post

### ISSUE THREAD

**Issue by Metrix1010** [OpenMined/writing#185]
We need an update to the links and content of this blog post from Nov 2020. Should be a quick review.

https://blog.openmined.org/duet-opengrid-infrastructure-for-easy-remote-data-science/

**Comment by Sukanya-rs** [comment]
I can work on this. Please assign it to me.

**Comment by Sukanya-rs** [comment]
The links that were inaccessible are updated. Tried working on the content with syft 0.5.0, it works perfectly fine. Checked with Madahava Jay on duet not working on 0.6.0. Clarification was provided that course 2 "Foundations of private computation" docs will be updated soon with information that users need to use 0.5.0 explicitly when 0.6.0 comes out officially. Hence, We can close this issue.
