### ISSUE TITLE
MICCAI PPML workshop paper summary

### ISSUE THREAD

**Issue by AbinavRavi** [OpenMined/writing#186]
Paper 1: Defending Medical Image Diagnostics against Privacy Attacks using Generative Methods

**Comment by AbinavRavi** [comment]
The paper can be found [here](https://arxiv.org/abs/2103.03078). A blog post summarizing the hypothesis and findings need to be written.

**Comment by plau51ble** [comment]
Hi Abinav. I would like to write this one if it is still open. - Gatha

**Comment by plau51ble** [comment]
This issue can be closed. Please find the article here: https://blog.openmined.org/can-privacy-of-medical-images-be-ensured-through-proxy-data/

**Comment by Metrix1010** [comment]
@AbinavRavi can this issue be closed?
