### ISSUE TITLE
Data behavior

### ISSUE THREAD

**Issue by Metrix1010** [OpenMined/writing#189]
How do I know the dataset I am using is the data I want? Synthetic data and validating expected behavior of the data.

**Comment by plau51ble** [comment]
Hi Laura! Can you please assign this issue to me? Thanks - Gatha

**Comment by Metrix1010** [comment]
It is all yours Gatha! Thanks :)

**Comment by plau51ble** [comment]
This issue can be closed now. Please find the post at: https://blog.openmined.org/is-my-fake-data-real-enough/
