### ISSUE TITLE
Blog: If I wanted to get a copy of all of my data from every company - what would I do?

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#19]

**Comment by ZinaSar** [comment]
@em-blue , Dear Emma, I would like to get assigned this Issue.

**Comment by ZinaSar** [comment]
@em-blue , do we have a link to the videos?

**Comment by mistryishan25** [comment]
@em-blue, Is it about how an individual can approach the companies formally, or are we writing about the platform "Saymine"(described in the course 1), as to how it abstracts the formal process and makes it easier?

**Comment by Metrix1010** [comment]
Hi @mistryishan25 can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
