### ISSUE TITLE
Learnings from Openmined course 1, Our Privacy Opportunity for Non technical people

### ISSUE THREAD

**Issue by AbinavRavi** [OpenMined/writing#190]
1. the privacy/transparency dilemma
2. Use cases and commercial Opportunities

**Comment by rachelproductmanager** [comment]
Hi I'd like to claim this, thanks

**Comment by AbinavRavi** [comment]
The post is now a series and the first post of the series can be found here - https://blog.openmined.org/datas-fundamental-trade-off/

**Comment by Kiaka007** [comment]
Design asset has been made for showing components of structured transparency.
https://github.com/OpenMined/design/blob/assets/diagrams/structured-transparency.jpg

**Comment by AbinavRavi** [comment]
Blog is published as 3 part series
- https://blog.openmined.org/datas-fundamental-trade-off/
- https://blog.openmined.org/lessons-from-our-privacy-opportunity-part-2/
- https://blog.openmined.org/pets-real-world-use-cases/
