### ISSUE TITLE
Privacy Teaching series: Explain and demonstrate a domain node concept

### ISSUE THREAD

**Issue by AbinavRavi** [OpenMined/writing#192]
Explain what domain node in RDS is?
A small demo on how the domain node is deployed and used by data scientist

Refer L2 of course 3

**Comment by Sukanya-rs** [comment]
Please assign this to me. Thank you.

**Comment by AbinavRavi** [comment]
Published as a 3 part blog series
- https://blog.openmined.org/remote-data-science-part-1-todays-privacy-challenges-in-bigdata-2/
- https://blog.openmined.org/remote-data-science-part-2-introduction-to-pysyft-and-pygrid/
- https://blog.openmined.org/remote-data-science-part-3-deploying-a-single-domain-node/

**Comment by Sukanya-rs** [comment]
Please close this issue as all the blogs are published.
