### ISSUE TITLE
Writing Team Application update

### ISSUE THREAD

**Issue by Metrix1010** [OpenMined/writing#199]
Elements to add:
- [ ] Interest in hosting monthly meetings
- [ ] Time zone region: primary & secondary
- [ ] Employed? list Company & Role
- [ ] Ways to contribute select: writing research papers, opinion pieces, editing for technical accuracy, editing for English language usage, translating to another language, program highlight pieces.

**Comment by Arya-Gupta** [comment]
I am interested in working on this issue. Can I be assigned?

**Comment by Metrix1010** [comment]
Hi @Arya-Gupta 

My apologies, this idea has been captured elsewhere. My fault for not tidying this up! 
Is there another way you'd like to contribute?

Thanks for your interest!
