### ISSUE TITLE
Code demo: Differential Privacy Use-Case in a huge dataset of URLs from facebook

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#39]
Differential Privacy Use-Case in a huge dataset of URLs from facebook (https://socialscience.one/blog/unprecedented-facebook-urls-dataset-now-available-research-through-social-science-one) Codebook, paper that goes into detail on how they used DP to be GDPR complaint: https://socialscience.one/url-shares-codebook

**Comment by Sukanya-rs** [comment]
Please assign this issue to me.

**Comment by Metrix1010** [comment]
Hi @Sukanya-rs can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
