### ISSUE TITLE
Blog: Article on Renyi Differential Privacy

### ISSUE THREAD

**Issue by kammitama5** [OpenMined/writing#4]
Krystal is working on this

**Comment by balapriyac** [comment]
Hi @kammitama5 could you pls update me on the status of this post. : )

**Comment by Metrix1010** [comment]
Hi @kammitama5 can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
