### ISSUE TITLE
Code demo: Tutorial on using federated learning alongside DP-SGD

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#58]

**Comment by balapriyac** [comment]
Hi @Harkirat155 hope you're working on the post, and your draft is coming along. Pls feel to reach out to the team on Slack if you need any assistance.

**Comment by Metrix1010** [comment]
Hi @Harkirat155 can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
