### ISSUE TITLE
Privacy Teaching Series: What is Static vs Dynamic Federated Learning?

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#61]
This has been asked a lot frequently - @cereallarceny I think it'd be good to explain this in a quick blog post to save you time re-explaining. Or perhaps 'model centric' vs 'data centric' or however you'd like to classify. Thoughts?

**Comment by cereallarceny** [comment]
We will get around to this, yes. I’ll have this in time. In short, here’s the difference:

**Federated learning**: training or inference of a model on data where the model and data exist in separate locations
**Static federated learning**: federated learning where the model is hosted in a central location and the data is at the edge (in a web browser or on a mobile device)
**Dynamic federated learning**: federated learning where the data is hosted in a central location and the model is at the edge (created by a data scientist)

**Comment by Kritikalcoder** [comment]
I'd love to help with this

**Comment by cereallarceny** [comment]
As would I! @Kritikalcoder @em-blue

**Comment by em-blue** [comment]
Thanks @cereallarceny I'll be marking this as closed as it's covered in your latest :-) https://blog.openmined.org/announcing-new-libraries-for-fl-on-web-and-mobile/
