### ISSUE TITLE
Blog: How to protect your privacy (right now)

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#62]
Write a post about all the tools you should use to protect your privacy (brave browser, VPNs, etc.)"

**Comment by jabertuhin** [comment]
[Google Doc Link](https://docs.google.com/document/d/1LhNjMPTZJSgMc76z43rQiaU2oSugYIj_7hY09l1dfvc/edit?usp=sharing)

**Comment by jabertuhin** [comment]
Blog post - [HOW TO PROTECT YOUR PRIVACY ONLINE (RIGHT NOW)?](https://blog.openmined.org/how-to-protect-your-privacy-online-right-now/)
