### ISSUE TITLE
Blog: Why selling data is bad - but selling data derivatives could be good

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#63]
Why selling data is bad - but selling data derivatives could be good. Useful links: https://twitter.com/aprilaser/status/1233023547867574272 , https://www.youtube.com/watch?v=4zrU54VIK6k

**Comment by edoroth** [comment]
Hey! Started thinking about this today before I noticed you assigned. My (very initial) thoughts:
https://www.notion.so/Selling-Invididual-Data-vs-Data-Derivatives-65984ca2f6464b589d6104cf86a777fe

**Comment by jabertuhin** [comment]
Hello @edoroth,
If you have already started working on this, then you should continue. And I will pick something else.

**Comment by edoroth** [comment]
Alright thanks, and sorry for the confusion! But I am also happy to collaborate on it if you have any thoughts.
  
  

  
>

**Comment by jabertuhin** [comment]
No problem.
If I come across any article on the above topic, I will share it here.

**Comment by Metrix1010** [comment]
Hi @edoroth can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
