### ISSUE TITLE
Code Demo: Encrypted Machine Learning as a Service using PyGrid and PyTorch

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#66]

**Comment by Metrix1010** [comment]
Hi @socd06 can you provide a status update on this issue?

**Comment by salgadev** [comment]
Hi Laura, sorry I haven't worked on this. I was promised a paid position a
while ago and then I received no feedback so I totally forgot. Also I don't
have time right now unless it's paid work. Thanks
