### ISSUE TITLE
List of companies/startups in the privacy space

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#70]

**Comment by cescapa** [comment]
Mine saymine.com, Acuratio, Privacera, Privsee, Black Fog, Intellegant, Privally, Immuta, Privitar, Bitnobi, Privaon, DataFleets, DataGrail, SelectOut, DataGravity, Apheris, Dataguise, DataTrue, Atomite, Globig, Datastream.io, HITRUST, Mighty Trust, OneTrust, Pryv, trust-hub, TrustArc, The Media Trust, PrivacyProtector, SecureB2B, Didomi, Securiti.ai, Security Scorecard

**Comment by zredlined** [comment]
And Gretel https://gretel.ai 😉. For others in the privacy / synthetic data space there are mostly.ai and datafleets. In the messaging space, there's Signal too.

**Comment by em-blue** [comment]
Hey @zredlined and @cescapa, we did a version of this one here and decided to crowd source the list (we've got a little over 300 companies in the airtable now). Feel free to add some via the form in this article if the ones you've mentioned aren't already on there!

https://blog.openmined.org/list-of-companies-in-privacy/

Hope you enjoy the resource :)
