### ISSUE TITLE
Differential Privacy Basics Part 1: Introduction + Randomized Response

### ISSUE THREAD

**Issue by Kritikalcoder** [OpenMined/writing#75]
Components:

Motivation: why DP?
Randomized response
Introduction to DP
Example database + query on it (simple use case)

**Comment by ZumrutMuftuoglu** [comment]
On-going blog post. You can find draft link in the following:
https://medium.com/@zmuftuoglu/step-by-step-towards-the-differential-privacy-randomized-response-in-privacy-a6c361008ff

**Comment by ZumrutMuftuoglu** [comment]
It has completed and needed for editor review . 
https://medium.com/@zmuftuoglu/step-by-step-towards-the-differential-privacy-randomized-response-in-privacy-review-version-e21b1e437ee7

**Comment by AbinavRavi** [comment]
@ZumrutMuftuoglu Do you have access to the openmined ghost so that we can publish it in the blog. If not please contact me on Slack. Thanks
