### ISSUE TITLE
Differential Privacy Basics Part 2: Definitions

### ISSUE THREAD

**Issue by Kritikalcoder** [OpenMined/writing#76]
Components:

1. Definition of epsilon-DP and epsilon,delta-DP
2. Intuition behind DP
3. Privacy budget: epsilon & delta

**Comment by shaistha24** [comment]
Hey! I would like to take this up! Is someone working on it?! 
@edoroth are you working on it?!

**Comment by edoroth** [comment]
No, go for it!
  
  
  
 Thanks,  
Edo
  
  
  
  

  
  
>

**Comment by shaistha24** [comment]
Waiting to be reviewed - https://blog.openmined.org/p/23610ee2-1fcd-4318-9857-94f7ef5cfa04/

**Comment by shaistha24** [comment]
Published

**Comment by Metrix1010** [comment]
@AbinavRavi what is the status of this issue?

**Comment by AbinavRavi** [comment]
Issue is closed since blog is published and I removed all the status @Metrix1010
