### ISSUE TITLE
Differential Privacy Advanced Part 1: Strengths & Weaknesses

### ISSUE THREAD

**Issue by Kritikalcoder** [OpenMined/writing#82]
Components:

1. Different types of noise mechanisms
2. Strengths n weaknesses
3. How to choose noise mechanisms based on use case
4. Data Dependent DP

**Comment by BhaswatiRoy** [comment]
Hello
I would like to work on this issue
It would be great if this could be assigned to me
Thanks!

**Comment by Metrix1010** [comment]
https://blog.openmined.org/differential-privacy-advances-part-1-strengths-weaknesses/
Thank you @BhaswatiRoy !
