### ISSUE TITLE
Blog: An explanatory blog post of the difference between Anonymization & Pseudonymization, which could be a reference for people not very technical to better understand. With concrete examples on simple data.

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#90]
This was suggested by Theo Ryffel - ask him for clarification or suggestions!

**Comment by Metrix1010** [comment]
Hi @divyadixit can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
