### ISSUE TITLE
Blog: In case you missed it: Summary blog from the OpenMined Research Team Presentations - July 25th Presentations (written using the video recording)

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#91]

**Comment by em-blue** [comment]
Hey @shaistha24 @znreza @murugeshmanthiramoorthi  - All 3 of you expressed interest in this one, DM me your email addresses and I'll forward the recording of the talks. I'll change this issue to be this particular month's video, and you can decide amongst the three of you whether you'd like to trade months or split up the recording each month, etc :-)

**Comment by shaistha24** [comment]
Done - https://blog.openmined.org/research-presentations-25-july-2020-talk-summary/
