### ISSUE TITLE
Blog: In case you missed it: Summary blog highlighting content from Fatemeh's AMA (written using the video recording)

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#94]
Write a blog post highlighting the coolest parts from Fatemeh's Ask Me Anything video (https://www.youtube.com/watch?v=6n39SrGuCAg)! For example, here's what Emma wrote from Ionesio's AMA: https://blog.openmined.org/what-is-pygrid-demo/

**Comment by dA505819** [comment]
@em-blue This interest me! Please assign me the issue.

**Comment by em-blue** [comment]
@dA505819 done! :-)

**Comment by Metrix1010** [comment]
Hi @dA505819 can you provide a status update on this issue?

**Comment by dA505819** [comment]
@Metrix1010 I think It completely skipped out of mind. Than you for reminding. Is that we can take on priority basis or can be done in a week's time?

**Comment by Metrix1010** [comment]
@dA505819 Just wanted an update :)  If you are still planning to work on it that's great! You can also unassign yourself if you haven't got the bandwidth.

**Comment by dA505819** [comment]
Hi @Metrix1010 ! Can you please reassign it to someone else? The bandwidth for an article is not their in coming days.

Thank you for checking:)

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
