### ISSUE TITLE
Blog: In case you missed it: Summary blog highlighting content from Alan's AMA (written using the video recording)

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#96]
Write a blog post highlighting the coolest parts from Alan's Ask Me Anything video (https://www.youtube.com/watch?v=gtwOPxxJ5F4)! 

For example, here's what Emma wrote from Ionesio's AMA: https://blog.openmined.org/what-is-pygrid-demo/

**Comment by cescapa** [comment]
@oudarjya718 is this issue still active? I can offer to review if so. please advise (or close issue if no longer applicable)

**Comment by ghost** [comment]
Hi @cescapa  This blog has been  published , 
 I'm closing then issue!
