### ISSUE TITLE
Blog idea: "Dollars for data" - where do privacy tools fit in this debate? (response to this podcast: https://www.flashforwardpod.com/2020/07/21/dollars-for-data/)

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#97]
Feel free to adapt idea toward whatever inspires you

**Comment by Metrix1010** [comment]
Hi @gual can you provide a status update on this issue?

**Comment by gual** [comment]
@Metrix1010 Sure. It wasn't done because my availability changed and I wasn't able to finish it.
