### ISSUE TITLE
Blog idea: Privacy vs Monetization - do privacy tools offer a third choice in the 'own your data' debate? Watch this talk and respond: https://www.youtube.com/watch?v=JIo-V0beaBw

### ISSUE THREAD

**Issue by em-blue** [OpenMined/writing#99]
Feel free to adapt idea toward what interests you

**Comment by Manikanta-Sangu** [comment]
@em-blue Will take this up

**Comment by Manikanta-Sangu** [comment]
@em-blue Draft for this issue: https://docs.google.com/document/d/12ybSRJsEey07bDssVJU1kd9kNhyAjuinic2FpYaoGxo/edit?usp=sharing

Let me know the next steps. Thanks

**Comment by cescapa** [comment]
@Manikanta-Sangu  is this issue still active and do you need any further editing assistance?

**Comment by Manikanta-Sangu** [comment]
I had a break. This has been reviewed once and some changes were suggested. Will complete this in one week.

**Comment by cescapa** [comment]
how are you getting on @Manikanta-Sangu ? I can help editing this coming weekend if you have a draft. Here are some notes in case they are helpful: 
- This TED talk was delivered by Stuart Lacey five years ago: Dec 2015
- All our digital activity generates a trail of 0's and 1's associated with personal profiles that companies build about us
- Personal data is a product whose value can be calculated by user (in 2015, Google: $200, FB: $116)
- There is a 3-way standoff between Big Data companies, IOT device makers, and government regulators
- Companies erect barriers: very complex license agreements (iTunes: 20745 words in 36 pages), privacy-invasive features turned on by default (Samsung TV: camera/microphone enabled) and very complex menus to change default settings
- Regulators are acting but generally on the back foot 
- Per regulation PII cannot be moved around, so it is anonymised and then remade identifiable using analytical and AI tools in a complex and expensive process
- Big Tech thus become middlemen connecting consumers and providers by leveraging our personal profile and digital activity 
- Stuart Lacey predicted that PII can be monetised and that Big Data can be disintermediated
I think that the answer to Emma's question is "not yet" ;)

**Comment by Manikanta-Sangu** [comment]
Thanks @cescapa. I have worked on the same. I also addressed the valuable feedback provided by @nahuakang on the first version.

@cescapa @nahuakang Please review the second version.

https://docs.google.com/document/d/12ybSRJsEey07bDssVJU1kd9kNhyAjuinic2FpYaoGxo/edit?usp=sharing

**Comment by cescapa** [comment]
> Thanks @cescapa. I have worked on the same. I also addressed the valuable feedback provided by @nahuakang on the first version.
> 
> @cescapa @nahuakang Please review the second version.
> 
> https://docs.google.com/document/d/12ybSRJsEey07bDssVJU1kd9kNhyAjuinic2FpYaoGxo/edit?usp=sharing

comments made - please check Slack also

**Comment by cescapa** [comment]
How are you doing @Manikanta-Sangu ? Are you still active in this article?

**Comment by Metrix1010** [comment]
Hi @Manikanta-Sangu and @nahuakang can you provide a status update on this issue?

**Comment by Metrix1010** [comment]
Stale topic. Please create a new issue if you've been working on it and want to proceed.
A new spin off this topic might be how new Privacy Laws affect monetization of data and how industry sectors are navigating those parameters. Either way, start a new issue.
